### ISSUE TITLE
Support dynamic table name

### ISSUE THREAD

**Issue by jilen** [sorm/sorm#38]
I have a two table `account_0` and `account_1`, and ,I have and `Account` class. I haven't found any way to insert the `Account` into the account_x table according its account_id(actually the suffix is account_id % 2)

**Comment by rutvik-bapat** [comment]
https://github.com/
https://github.com
https://github.com
https://github.com
https://github.com
https://github.com
https://github.com
https://github.com
https://github.com
https://github.com/////////
