### ISSUE TITLE
Scala 2.11.* support

### ISSUE THREAD

**Issue by daron666** [sorm/sorm#46]
Is there any chance to update Sorm for Scala 2.11 version?

**Comment by csachs** [comment]
Would be great if a new release with scala 2.11 compatibility could be pushed.
I perfomed 14ae225594eeeeb946640d786dcbfcee617b3cc7

**Comment by nikita-volkov** [comment]
@csachs Thank you! I'll review and merge it in the coming days.

**Comment by nikita-volkov** [comment]
Fixed in 0.3.16. Special thanks to @csachs!
