### ISSUE TITLE
Searching in the database with ignore-case option

### ISSUE THREAD

**Issue by marad** [sorm/sorm#48]
I would like to have the ability to search the string values in the database with ignore case option. I can't see it in provided DSL.

The easiest would probably be to create something like:

```
"title" likeIgnoreCase "%something%"
```

other option could be:

```
upper("title") like upper("%something%")
```

but this is kinda recreating SQL syntax.

**Comment by nikita-volkov** [comment]
Sorry. For some reason I missed this issue.

I suppose you implied Postgres. Since SORM 0.3.18, the `LIKE` operator in Postgres driver is case-insensitive.
