### ISSUE TITLE
Legacy database - no column 'id'

### ISSUE THREAD

**Issue by wnadurski** [sorm/sorm#59]
> What should you do when you need to specify the id yourself?
> 
> Nothing. You shouldn’t do that. The id property is supposed to be generated and managed by db only. If you need to specify some external unique identifier, like, for instance, Amazon’s ASIN, just add an appropriate field to your entity and specify it as unique on SORM instantiation.

Guys. What if I have legacy database, where there is no column 'id' in any table, but their's primary keys have other names, and many other applications uses this database so i just can't change primary key to new column 'id'? What should I do?

**Comment by nikita-volkov** [comment]
SORM provides no way to customise the mapping to the database, so if you have no way to adapt your schema to SORM's requirements, I'm afraid, it's simply not an option for you.

**Comment by wnadurski** [comment]
Thanks

**Comment by bthibault** [comment]
is it possible to open this as an improvement, I feel like this is necessary to do explicit mappings sometimes, as not everyone starts on a greenfields project. Also would be nice to map caseclass name to a specific table.

**Comment by nikita-volkov** [comment]
As soon as we start doing this, we open the doors to the classical enormous configuration problems of ORMs. There's an impedance mismatch between the relational and object model, so the manual configuration is guaranteed to be painful for both the library devs and its users.

Honestly, in such cases as yours I'd advice just going directly with a good SQL library, never an ORM.
