### ISSUE TITLE
 Unsupported type: models.Host with sorm.Persisted

### ISSUE THREAD

**Issue by olivierdu95** [sorm/sorm#68]
Hi,

i am currently trying to save data of a Seq who depend of an other model 

`
case class Host (hostIp : String,portlist : Seq[Port],lastscan : Long){
    for ( i<- 0 until portlist.length){
     DB.save(portlist(i));
    }
  val persistedHost = DB.save(Host(hostIp,portlist,lastscan));
}
`

But when i start my playframework projet this error appear : 
Unsupported type: models.Host with sorm.Persisted

Can someone help me ? ;(
thank you in avance

**Comment by nikita-volkov** [comment]
Check if you have registered all the appropriate entities with the DB instance.

**Comment by olivierdu95** [comment]
Hello nikita,

thanks for your answer, here my entitites :
`package models

 import play.api.Play.current
 import sorm._

object DB extends Instance(
    entities = Set(Entity[Network](),Entity[Host](),Entity[Port]()),
      url = "jdbc:h2:mem:default",
      user = "sa",
      password = ""
      )
`
and my database : 

`CREATE TABLE NETWORK (
	ID		INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NETWORK_NAME	VARCHAR(50)		,
	NETWORK_IP		VARCHAR(50) NOT NULL,
	NETWORK_MASK	INT    
);

CREATE TABLE HOST (
	ID		INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	HOST_IP		VARCHAR(50) NOT NULL,
   	LASTSCAN    INT
);
CREATE TABLE PORT (
	ID		INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PORT_NUMBER		INT NOT NULL,
);
`

**Comment by nikita-volkov** [comment]
Wait a minute. You're doing some mess in the constructor of `Host`, while it should be just a plain case class. That's the reason.

**Comment by olivierdu95** [comment]
in this case, how to save Seq of `Port` into Host ?

**Comment by nikita-volkov** [comment]
See the quick intro http://sorm-framework.org/
