### ISSUE TITLE
Unable to add id of to JsonObject

### ISSUE THREAD

**Issue by DjamshidDjurayev** [sorm/sorm#70]
i can't add "id"  to a jsonobject field. i need this:
{
id: 1,
name: "Джамшид",
surname: "Джураев",
login: "djamik123",
password: "djamik123"
}

instead i get this: without id
{
name: "Джамшид",
surname: "Джураев",
login: "djamik123",
password: "djamik123"
}

**Comment by nikita-volkov** [comment]
From [the documentation](http://sorm-framework.org/Documentation.html):

> Since the `id` property value is meant to be generated by database, it is protected from the user of being able to manually specify it as well as letting the case classes have such a property.
> 
> So, instead of
> 
> ```scala
> case class Artist ( id : Long, name : String )
> ```
> 
> you should use
> 
> ```scala
> case class Artist ( name : String )
> ```
> 
> and let SORM take care of `id` property management for you.
