### ISSUE TITLE
support for specifying min pool size

### ISSUE THREAD

**Issue by pjfanning** [sorm/sorm#75]
It would be useful in some cases to allow users to specify a minPoolSize as well as a maxPoolSize.

**Comment by nikita-volkov** [comment]
Can you provide the motivation?

**Comment by pjfanning** [comment]
I realise that most users will be happy with a minPoolSize of 1 but we have a use case where we separate our data into separate tenant databases. Our application will have separate Sorm/C3P0 connection pools per database. In theory, we could have 100s of connection pools and it would be good in our case that all idle connections were closed.

**Comment by nikita-volkov** [comment]
Okay. So basically what you want is to be able to set `minPoolSize` to `0`, right? I don't mind changing the setting to that internally without changing the API.

**Comment by pjfanning** [comment]
Thanks Nikita. That simpler change suits my use case.

**Comment by nikita-volkov** [comment]
Fixed in 0.3.20
