### ISSUE TITLE
Get id of nested class when querying

### ISSUE THREAD

**Issue by andrewsim** [sorm/sorm#89]
I'm following the example in the documentation:
```scala
case class Genre ( name : String )
case class Artist ( name : String, genres : Set[Genre] )

val metal : Genre with Persisted  = Db.save(Genre("Metal"))
val metallica : Artist with Persisted  = Db.save(Artist("Metallica", Set(metal)))
```

And to retrieve the record:
```scala
val artist = Db.query[Artist].whereEqual("name", "Metallica").fetchOne() 
```

Now`artist` have type `Artist with Persisted`, I can extract the `id` just fine. 
However, `artist.genres` has type `Set[Genre]` and not `Set[Genre with Persisted]`, is it possible to extract the `id` from any of the `artist.genres`?

**Comment by nikita-volkov** [comment]
Try casting it. E.g.,
```scala
artist.genres.map(_.asInstanceOf[Persisted].id)
```

**Comment by andrewsim** [comment]
casting it works, a bit unsafe but it works, closing this issue now, thanks @nikita-volkov
