### ISSUE TITLE
Website Down?

### ISSUE THREAD

**Issue by talnicolas** [sorm/sorm#91]
It seems like the website has expired on Nov. 1st, we can't access the documentation anymore... could the doc be moved to that repository?

**Comment by nikita-volkov** [comment]
Wooops! Sorry for that. Somehow missed the notifications about having to extend it.

Anyway, it's now payed for so it should come back soon.

**Comment by talnicolas** [comment]
Thank you very much!

**Comment by nikita-volkov** [comment]
No prob! Thanks for reporting!
